[HOPSWORKS-2303] Change python pip search to use pypi simple index and JSON API
logicalclocks/elasticsearch-chef pull request #55
Opened 2021-02-11 13:18 UTC by robzor92

2021-02-15 12:26 UTC, o-alex requested changes

2021-02-15 12:26 UTC, o-alex commented on providers/start.rb
> +            "type":"keyword"
also do you have multiple versions of a library? did you try making them into an array, so you can compress multiple docs in just one? 
you can query it afterwards as such: https://discuss.elastic.co/t/how-to-query-a-multi-value-field/14671

2021-02-16 09:43 UTC, robzor92 commented on providers/start.rb
> +            "type":"keyword"
![Screenshot from 2021-02-16 10-23-41](https://user-images.githubusercontent.com/9936580/108045456-c418a000-7043-11eb-919a-0db6c36c474d.png)

2021-02-16 09:47 UTC, robzor92 commented on providers/start.rb
> +            "type":"keyword"
It doesn't seem to be limited to only exact matches. I'm going to test using the text field too and see what the difference is. I'm not sure if it matters that much if you have text or keyword when it is a single term. From what I understand if you set the field to text it will index each term separately, while keyword will not. But if you have a single term the indexing for keyword and text is the same as they both will index a single term.

2021-02-16 09:48 UTC, robzor92 commented on providers/start.rb
> +            "type":"keyword"
I don't have multiple versions of a library. Only one doc for each library name. The versions themselves are retrieved in a later call to pypi directly.

2021-02-16 12:40 UTC, robzor92 commented on providers/start.rb
> +            "type":"keyword"
![Screenshot from 2021-02-16 13-38-40](https://user-images.githubusercontent.com/9936580/108064080-752b3480-705c-11eb-9faa-b5484ee99f32.png)

2021-02-16 12:41 UTC, robzor92 commented on providers/start.rb
> +            "type":"keyword"
If I set the library field as `text` I'm getting the same hits back from my fullTextQuery. I tried some other queries too and I get the same hits as with the `keyword` field.

2021-02-17 09:52 UTC, o-alex approved these changes

2021-02-22 09:50 UTC, merged