[HOPSWORKS-2382] Collect services logs in Elastic
logicalclocks/elasticsearch-chef pull request #60
Opened 2021-08-09 17:42 UTC by SirOibaf

2021-08-23 12:22 UTC, o-alex requested changes

2021-08-23 12:22 UTC, o-alex commented on providers/start.rb
> +                "type":"text"
are you sure you need to create priority as text and KEYWORD is not enough? are you going to run partial matches on this? seems to me like you will always search by enum like constructs: DEBUG/INFO

2021-08-23 12:22 UTC, o-alex commented on templates/default/roles.yml.erb
> +      - ".services-*"
As I pointed in the pm on slack, this roles index pattern is at odds with the one in the elastic pattern definition where you set it as:
 `"index_patterns":[
    "*.services-*"
 ]`

2021-08-23 12:22 UTC, o-alex commented on templates/default/roles.yml.erb
> +      - ".services-*"
same as above with the pattern issue

2021-09-07 13:49 UTC, SirOibaf commented on templates/default/roles.yml.erb
> +      - ".services-*"
`.services-*` is the correct one. One index for all the logs.

2021-09-07 13:49 UTC, SirOibaf commented on templates/default/roles.yml.erb
> +      - ".services-*"
Same as above.

2021-09-07 13:49 UTC, SirOibaf commented on providers/start.rb
> +                "type":"text"
Done.

2021-09-10 09:18 UTC, o-alex approved these changes

2021-09-10 09:40 UTC, kouzant approved these changes

2021-09-13 06:56 UTC, merged