[HOPSWORKS-2794]Use templates for code indices and enable expat reindexing
logicalclocks/elasticsearch-chef pull request #67
Opened 2021-10-28 14:06 UTC by o-alex

2021-11-16 12:46 UTC, SirOibaf requested changes

2021-11-16 12:46 UTC, SirOibaf commented on recipes/default.rb
> +end
You don't need to move this - as the backup directory is something that we just created, it doesn't exists on existing clusters.

2021-11-16 14:08 UTC, o-alex commented on recipes/default.rb
> +end
ok, removed this part.

2021-11-16 23:29 UTC, SirOibaf approved these changes

2021-11-17 12:59 UTC, maismail requested changes
@o-alex can you also remove the (reindex-base-indices.sh.erb) file and its references as part of your PR, basically revert the following commit 

https://github.com/logicalclocks/elasticsearch-chef/commit/289b7d1a1ebe294e6f23b1a982c4181bcd4b360f

2021-11-17 15:37 UTC, o-alex commented
@maismail reverted that PR and removed some variables as well that were there just for the script itself

2021-11-17 16:16 UTC, maismail approved these changes

2021-11-18 12:54 UTC, merged