[HOPSWORKS-3157] Add indexes for onlinefs logs
logicalclocks/elasticsearch-chef pull request #81
Opened 2022-06-14 14:40 UTC by gibchikafa

2022-08-29 07:43 UTC, bubriks approved these changes

2023-07-05 12:53 UTC, bubriks commented on providers/start.rb
> +             }
```suggestion
             "host":{
                "type":"text"
             },
             "log_arguments":{
                "type":"object"
             }
```

2023-07-05 13:07 UTC, bubriks commented on providers/start.rb
> +             }
needed after changes in https://github.com/logicalclocks/clusterj-onlinefs/pull/72

2023-07-17 07:45 UTC, o-alex commented on templates/default/roles.yml.erb
> +      - "onlinefs_${attr.jwt.projid}-*"
same comment from hopsworks-ee. This adds a new index per project... is this acceptable in cloud (serverless)?

2023-07-17 08:26 UTC, o-alex approved these changes

2023-07-24 09:13 UTC, SirOibaf requested changes
Need to fix the mapping to match the new log_argument pattern before merging.

2023-08-01 17:57 UTC, gibchikafa commented
New pr is https://github.com/logicalclocks/elasticsearch-chef/pull/105

2023-08-01 17:57 UTC, closed without merging